<?php
$z[0]=Array("global","",103,130);
$z[0][4]['name']="cfg_basehost";
$z[1]=Array("global","",132,158);
$z[1][4]['name']="cfg_webname";
$z[2]=Array("global","",223,248);
$z[2][4]['name']="cfg_cmsurl";
$z[3]=Array("global","",385,413);
$z[3][4]['name']="cfg_memberurl";
$z[4]=Array("global","",472,497);
$z[4][4]['name']="cfg_cmsurl";
$z[5]=Array("global","",562,588);
$z[5][4]['name']="cfg_dataurl";
$z[6]=Array("global","",660,686);
$z[6][4]['name']="cfg_dataurl";
$z[7]=Array("global","",1095,1120);
$z[7][4]['name']="cfg_cmsurl";
$z[8]=Array("channel","\r\n      	<li><a href='[field:typeurl/]' [field:rel/]>[field:typename/]</a></li>\r\n      	",1147,1364);
$z[8][4]['type']="top";
$z[8][4]['row']="10";
$z[8][4]['currentstyle']="<li class='hover'><a href='~typelink~' ~rel~>~typename~</a></li>";
$z[9]=Array("field","",1437,1464);
$z[9][4]['name']="phpurl";
$z[10]=Array("tag","<li><a href='[field:link/]'>[field:tag /]</a></li>\r\n          ",2146,2261);
$z[10][4]['row']="8";
$z[10][4]['getall']="1";
$z[10][4]['sort']="month";

?>